### PR TITLE
Add fits-servlet to fits role

### PR DESCRIPTION
**Pull request by little9**
This adds changes to the fits role so that the
`fits-servlet` application is also installed. This involves
setting up Tomcat to run the war.

The role downloads the war and sets up tomcat
so that it will be run. The last task in the role
checks to see if it is running.

This role can be ran without running the fedora role
which also installs tomcat, or it can be run alongside
that fedora role.

### CODE REVIEW

**Comment by mark-dce** [comment]
@little9 Is this PR still relevant or should we close it?

**Comment by little9** [comment]
Let me make sure this allows for using both the old method and the new method before this merged.

**Comment by little9** [comment]
This is is ready to be merged. It will install fits-servlet in tomcat and also installs the version that is run manually. An application will need to be configured to use one of these versions (defaulting to the shell script).

**Comment by bess** [comment]
@little9 Can you confirm that this works if we're also installing fedora into Tomcat7?

**Comment by little9** [comment]
This role can be run before or after the other tomcat role. 

On tenejo-dev, I ran the role and you can make a request to fits like this: 
`curl http://localhost:8080/fits-1.2.0/`

It doesn't interfere with Fedora's installation. 

To get it working with Hyrax requires overrides that will need to be done in app (and environment variables set on the server):

https://github.com/UCLALibrary/californica/commit/92a12e1a4a9848f64800b178bbd2e7b50ec1a6f3#diff-6d03ef955dc6c480ec48beafa3d02080

**Pull request merged**
